import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {chromium} from 'playwright';
import {createApp} from '../server/app';
import {CATALOG} from '../packages/content/catalog';
import {candidates} from '../packages/rules';

const output=path.resolve('docs/evidence/table-feedback');
await mkdir(output,{recursive:true});
const app=await createApp({dataDir:await mkdtemp(path.join(tmpdir(),'showdown-ui-')),serveDir:path.resolve('dist'),now:()=>100000});
const base=await app.listen({host:'127.0.0.1',port:0});
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-webgl']});
try{
 const page=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'no-preference'});
 page.setDefaultTimeout(15000);
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const session=await (await fetch(base+'/api/matches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({seed:'flashcart-2026',names:['Alex','Sam']})})).json();
 const get=async(player=0)=> (await fetch(`${base}/api/matches/${session.id}`,{headers:{Authorization:`Bearer ${session.tokens[player]}`}})).json();
 const send=async(type:string,player:number)=>{
  const v=await get(player);
  const r=await fetch(`${base}/api/matches/${session.id}/command`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.tokens[player]}`},body:JSON.stringify({version:v.version,entry:{type}})});
  assert.equal(r.status,200);return r.json();
 };
 await page.goto(`${base}/?room=${session.id}&token=${session.tokens[0]}`);
 await page.locator('.hand-cards .game-card').first().waitFor();
 await page.locator('[data-node="api"]').waitFor();
 await page.waitForTimeout(1200);
 const cards=page.locator('.hand-cards .game-card'),before=await cards.first().boundingBox();
 assert.ok(before&&before.y>600);
 const node=page.locator('[data-node="api"]'),nodeBefore=await node.boundingBox();
 await page.mouse.move(790,590);for(let i=0;i<6;i++){await page.mouse.wheel(0,-140);await page.waitForTimeout(80);}await page.waitForTimeout(600);
 const zoomed=await cards.first().boundingBox(),nodeZoomed=await node.boundingBox();
 assert.deepEqual(zoomed,before,'A mão deve manter posição e tamanho durante o zoom');

 assert.ok(nodeZoomed!.width>nodeBefore!.width*1.1,'O zoom precisa aproximar a arquitetura');
 await page.screenshot({path:path.join(output,'desktop-zoom.png')});
 console.log('checking pan');await page.mouse.move(810,610);await page.mouse.down();await page.mouse.move(895,570,{steps:12});await page.mouse.up();await page.waitForTimeout(700);
 console.log('pan sent');const nodePanned=await node.boundingBox();
 assert.ok(Math.hypot(nodePanned!.x-nodeZoomed!.x,nodePanned!.y-nodeZoomed!.y)>30,'Arrastar vazio deve mover o tabuleiro');
 assert.deepEqual(await cards.first().boundingBox(),before,'Pan não deve mover a mão');
 console.log('checking recenter');await page.getByRole('button',{name:'Centralizar mesa'}).click();await page.waitForTimeout(600);
 const centered=await node.boundingBox();assert.ok(Math.abs(centered!.x-nodeBefore!.x)<2);
 console.log('checking protocol');const label=page.locator('[data-target="data"]');
 assert.equal(await label.locator('strong').innerText(),'SQL');
 const protocolFont=await label.locator('strong').evaluate(e=>parseFloat(getComputedStyle(e).fontSize));assert.ok(protocolFont>=9,'O rótulo de protocolo deve respeitar o mínimo de 9 px do HUD compacto');
 await label.hover();assert.ok(await label.locator('.edge-description').isVisible());
 await page.screenshot({path:path.join(output,'desktop-protocol.png')});
 console.log('checking planning');await send('ready',0);await send('ready',1);
 await page.waitForFunction(()=>document.querySelector('.scenario-current h2')?.textContent!=='Uma loja pronta para crescer');
 await page.waitForTimeout(1500);
 const briefing=page.getByRole('button',{name:'Entendi · ver tabuleiro'});if(await briefing.isVisible())await briefing.click();
 const v=await get(),card=v.player.hand.find((c:any)=>candidates(CATALOG[c.cardId],v.player.graph).some(t=>t.type==='node'));
 assert.ok(card);const target=candidates(CATALOG[card.cardId],v.player.graph).find(t=>t.type==='node')!;
 const dragCard=page.locator(`[data-card-instance="${card.uid}"]`);await dragCard.scrollIntoViewIfNeeded();
 const targetLocator=page.locator(`[data-target="${target.id}"]`);
 const handPositions=()=>page.locator('.hand-card-slot').evaluateAll(slots=>slots.map(slot=>slot.getBoundingClientRect().x));
 const originalPositions=await handPositions();let cb=(await dragCard.boundingBox())!;
 await page.mouse.move(cb.x+cb.width/2,cb.y+cb.height/2);await page.mouse.down();await page.mouse.move(cb.x+cb.width/2,cb.y+cb.height/2-24,{steps:4});
 await page.locator('.drag-card-floating.dragging').waitFor();await page.mouse.move(300,350,{steps:12});
 const collapsedPositions=await handPositions();assert.ok(collapsedPositions.some((x,index)=>Math.abs(x-originalPositions[index])>4),'As demais cartas devem fechar o espaço deixado pela carta arrastada');
 await page.mouse.up();await page.locator('.drag-card-floating.returning').waitFor();assert.equal(await page.locator(`[data-card-instance="${card.uid}"]`).count(),1,'O retorno também deve reutilizar a mesma carta');
 await page.locator('.drag-card-floating').waitFor({state:'hidden'});await page.waitForTimeout(320);
 const restoredPositions=await handPositions();assert.ok(restoredPositions.every((x,index)=>Math.abs(x-originalPositions[index])<2),'A mão deve recompor o leque após uma soltura inválida');
 cb=(await dragCard.boundingBox())!;const tb=(await targetLocator.boundingBox())!;
 await page.mouse.move(cb.x+cb.width/2,cb.y+cb.height/2);await page.mouse.down();await page.mouse.move(cb.x+cb.width/2,cb.y+cb.height/2-24,{steps:4});
 await page.locator('.drag-card-floating.dragging').waitFor();assert.ok(await page.locator('main.card-drag-dragging').isVisible(),'Arrastar deve ativar o estado visual da mesa');assert.equal(await page.locator('.card-inspector').count(),0,'A decisão só deve abrir depois de soltar');assert.equal(await page.locator(`[data-card-instance="${card.uid}"]`).count(),1,'O próprio card deve ser movido sem criar clone no DOM');assert.ok(await dragCard.isVisible(),'A mesma carta deve continuar visível enquanto acompanha o ponteiro');await page.waitForFunction(uid=>document.querySelector(`[data-hand-slot="${uid}"]`)!.getBoundingClientRect().width<4,card.uid);
 await page.mouse.move(tb.x+tb.width/2,tb.y+tb.height/2,{steps:15});await page.waitForFunction(id=>document.querySelector(`[data-target="${id}"]`)?.classList.contains('drop-active'),target.id);assert.ok(await targetLocator.evaluate(element=>element.classList.contains('drop-active')),'O encaixe sob a carta deve pulsar');await page.screenshot({path:path.join(output,'desktop-card-drag.png')});await page.mouse.up();
 await page.locator('.drag-card-floating').waitFor({state:'hidden'});
 console.log('checking drop');await page.getByRole('button',{name:'Preparar implantação'}).waitFor();
 assert.equal(await page.locator('.card-settings select').inputValue(),target.id);
 await page.getByRole('button',{name:'Preparar implantação'}).click();
 await page.waitForTimeout(700);
 await send('lock',0);await send('lock',1);
 await page.getByRole('region',{name:'Resultado da rodada 1'}).waitFor();
 await page.screenshot({path:path.join(output,'desktop-result-drag-regression.png')});
 await send('advance',0);await send('advance',1);await page.reload();
 await page.getByRole('region',{name:'Resultado da rodada 1'}).waitFor();
 assert.match(await page.locator('.measurement-caption').innerText(),/Resultado R1/);
 if(await briefing.isVisible())await briefing.click();
 for(const width of [766,390]){
  await page.setViewportSize({width,height:844});await page.waitForTimeout(1000);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Sem overflow horizontal');
  assert.equal(await cards.count(),(await get()).player.hand.length);
  if(width===766){assert.equal(await page.locator('.hand-navigation').evaluate(e=>getComputedStyle(e).display),'none','O leque compacto substitui a navegação lateral');}
  await page.screenshot({path:path.join(output,`${width}-round2.png`),fullPage:true});
 }
 assert.deepEqual(errors,[]);
 await writeFile(path.join(output,'checks.json'),JSON.stringify({passed:['zoom moves board and preserves hand bounds','pan moves board and preserves hand bounds','recenter restores camera','protocol name and description visible','single card DOM during drag','hand reflows on lift and invalid return','card drag and placement','round result survives advance and reload','766px and 390px without horizontal overflow'],browserErrors:errors},null,2));
 console.log('Browser: zoom, pan, fixed hand, protocols, single-card drag/return, drop, persistent results and responsive layouts passed.');
}catch(error){console.error(error);throw error;}finally{await browser.close();await app.close();}
