import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,CalendarDays,Copy,GitBranch,KeyRound,Play,Plus,Timer,Upload,Users} from 'lucide-react';
import {SPECIALTIES} from '../packages/content/catalog';
import type {DailyChallengeDefinition} from '../packages/domain/types';
import {api,requestId,type LobbyView,type Session} from './client';
import Tutorial from './Tutorial';
import './home.css';

export function HomeBrand(){return <div className="brand"><div className="brand-symbol"><GitBranch size={25}/></div><div>ARCHITECTURE DEVELOPER<strong>SHOWDOWN</strong></div></div>;}
export function Specialty({value,onChange,label='Especialização'}:{value:string;onChange:(v:string)=>void;label?:string}){return <label>{label}<select value={value} onChange={e=>onChange(e.target.value)}>{Object.entries(SPECIALTIES).map(([key,s])=><option key={key} value={key}>{s.name}</option>)}</select><small>{SPECIALTIES[value]?.description}</small></label>;}
export default function Home({onSession,onReplay,onResume,hasSession}:{onSession:(s:Session)=>void;onReplay:()=>void;onResume:()=>void;hasSession:boolean}){
 const [screen,setScreen]=useState<'menu'|'daily'|'solo'|'create'|'join'>(()=>new URLSearchParams(location.search).has('join')?'join':'menu');
 const [code,setCode]=useState(()=>new URLSearchParams(location.search).get('join')??''),[name,setName]=useState(''),[specialty,setSpecialty]=useState('balanced');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[tutorial,setTutorial]=useState(false),[daily,setDaily]=useState<DailyChallengeDefinition|null>(null),[now,setNow]=useState(Date.now());
 useEffect(()=>{let active=true;api('/challenges/daily').then(value=>{if(active)setDaily(value);}).catch(()=>{});const timer=setInterval(()=>setNow(Date.now()),60000);return()=>{active=false;clearInterval(timer);};},[]);
 async function submit(){setBusy(true);setError('');try{
   if(screen==='daily'){
    if(!daily)throw new Error('O desafio diário ainda está carregando.');const key=`showdown-daily-${daily.id}`;let id=localStorage.getItem(key);if(!id){id=requestId();localStorage.setItem(key,id);}
    const s=await api('/challenges/daily/start',{name,requestId:id});onSession({id:s.id,tokens:[s.token],mode:'daily',actor:0,online:false});return;
   }
   const fingerprint=JSON.stringify([screen,name,specialty,screen==='join'?code:'']);
   let pending:{fingerprint:string;requestId:string}|null=null;
   try{pending=JSON.parse(sessionStorage.getItem('showdown-admission')??'null');}catch{/* Replace invalid pending data. */}
   if(pending?.fingerprint!==fingerprint)pending={fingerprint,requestId:requestId()};
   sessionStorage.setItem('showdown-admission',JSON.stringify(pending));
   const s=await api(screen==='solo'?'/solo':screen==='create'?'/rooms':'/rooms/join',{name,specialty,requestId:pending.requestId,...(screen==='join'?{code}:{})});
   sessionStorage.removeItem('showdown-admission');history.replaceState(null,'',location.pathname);onSession({id:s.id,tokens:[s.token],mode:screen==='solo'?'solo':'remote',actor:0,online:screen!=='solo'});
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{window.scrollTo(0,0);},[screen]);
 const choose=(next:typeof screen)=>{setScreen(next);setError('');};
 return <main className="home-shell"><header className="home-header"><HomeBrand/><span className="home-edition">FLASHCART / 2 JOGADORES</span></header>
 <div className="home-grid"><section className="home-story"><p className="eyebrow">CONSTRUA. ADAPTE. ENFRENTE.</p><h1>Seu sistema.<br/>Suas decisões.<br/><em>O mesmo desafio.</em></h1><p>Uma loja em crescimento. Cinco contextos imprevisíveis. Construa uma arquitetura com cartas e descubra como ela se comporta sob pressão.</p><div className="home-diagram" aria-label="Arquitetura: clientes conectam à API, que conecta a dados e pagamentos"><span><Users/> CLIENTES</span><i/><span><GitBranch/> SUA API</span><i/><div><span>DADOS</span><span>PAGAMENTOS</span></div></div><div className="home-facts"><span>05 <small>rodadas</small></span><span>06 <small>testes finais</small></span><span>02 <small>arquiteturas privadas</small></span></div></section>
 <section className="home-panel" aria-label="Menu do jogo">{screen==='menu'?<><p className="eyebrow">SUA PRÓXIMA PARTIDA</p><h2>Escolha sua mesa</h2>{hasSession&&<button className="primary home-resume" onClick={onResume}><Play size={18}/> Retomar sessão</button>}
 <div className="home-options"><button className="daily-option" disabled={!daily} onClick={()=>choose('daily')}><CalendarDays/><span><strong>{daily?.title??'Preparando desafio diário'}</strong><small>{daily?`Desafio de ${new Intl.DateTimeFormat('pt-BR').format(new Date(`${daily.date}T12:00:00`))}`:'Carregando condições do dia'}</small></span><time className="daily-clock" dateTime={daily?.expiresAt?new Date(daily.expiresAt).toISOString():undefined} aria-label={daily?'Tempo restante aproximado do desafio':'Desafio ainda carregando'}><Timer size={12}/>{daily?`${Math.max(0,Math.ceil((daily.expiresAt-now)/3600000))}h`:'—'}</time><ArrowRight/></button><button onClick={()=>choose('solo')}><Play/><span><strong>Jogar contra IA</strong><small>Enfrente um arquiteto automático</small></span><ArrowRight/></button><button onClick={()=>choose('create')}><Plus/><span><strong>Criar sala</strong><small>Convide alguém com um código de acesso</small></span><ArrowRight/></button><button onClick={()=>choose('join')}><KeyRound/><span><strong>Entrar com código</strong><small>Conecte-se à sala de um amigo</small></span><ArrowRight/></button><button onClick={()=>setTutorial(true)}><BookOpen/><span><strong>Tutorial</strong><small>Aprenda as mecânicas, os custos e as regras</small></span><ArrowRight/></button></div><button className="text-button" onClick={onReplay}><Upload size={15}/> Reproduzir uma partida salva</button></>:<>
 <button className="text-button" disabled={busy} onClick={()=>choose('menu')}><ArrowLeft size={15}/> Voltar à home</button><p className="eyebrow">{screen==='daily'?'DESAFIO DIÁRIO':screen==='solo'?'VOCÊ × ARQUITETO IA':'MULTIPLAYER · 2 VAGAS'}</p><h2>{screen==='daily'?daily?.title:screen==='solo'?'Jogar contra IA':screen==='create'?'Criar sua sala':'Entrar na sala'}</h2><p className="home-hint">{screen==='daily'?daily?.publicBrief:screen==='solo'?'Escolha seu perfil e enfrente a IA em cinco rodadas. Ela monta a própria arquitetura, com os mesmos limites de EC e ações, sem ver suas cartas ou decisões.':'Cada jogador mantém sua mão e arquitetura privadas. Ambos precisam acessar este mesmo servidor.'}</p>
 {screen==='daily'&&daily&&<div className="daily-brief"><span>PERFIL DO DIA</span><strong>{SPECIALTIES[daily.specialty].name}</strong><ul>{daily.objectives.map(objective=><li key={objective.id}><b>{objective.label}</b><small>{objective.description}</small></li>)}</ul><p>A ordem dos contextos permanece oculta. A avaliação aparece somente no Showdown.</p></div>}
 {hasSession&&<p className="home-hint">Uma nova partida substitui a sessão salva nesta aba. <button className="text-button" onClick={onResume}>Retomar a anterior</button></p>}
 <form onSubmit={e=>{e.preventDefault();void submit();}}><fieldset disabled={busy}>{screen==='join'&&<label>Código de acesso<input className="code-input" value={code} onChange={e=>setCode(e.target.value.toUpperCase())} maxLength={16} autoComplete="off" autoCapitalize="characters" placeholder="ABCD2345" required/></label>}<div className="home-profile"><label>Seu nome<input value={name} maxLength={30} required autoComplete="nickname" onChange={e=>setName(e.target.value)}/></label>{screen!=='daily'&&<Specialty value={specialty} onChange={setSpecialty}/>}</div>{(screen==='solo'||screen==='daily')&&<p className="home-hint">Você tem 45 segundos por rodada. A partida continua no servidor se você desconectar.</p>}<button className="primary" disabled={busy||!name.trim()||(screen==='join'&&!code.trim())}>{busy?'Conectando…':screen==='daily'?'Iniciar desafio de hoje':screen==='solo'?'Começar contra IA':screen==='create'?'Criar sala':'Entrar na sala'}<ArrowRight size={16}/></button></fieldset></form>
 </>}{error&&<p className="home-error" role="alert">{error}</p>}</section></div><footer className="home-footer"><span>ESTRATÉGIA É COMPORTAMENTO, NÃO RECEITA.</span><span>Cartas · Conexões · Trade-offs</span></footer>{tutorial&&<Tutorial onClose={()=>setTutorial(false)}/>}</main>;
}

export function RoomLobby({lobby,busy,error,onAction,onHome}:{lobby:LobbyView|null;busy:boolean;error:string;onAction:(action:string,ready?:boolean)=>void;onHome:()=>void}){
 const [copied,setCopied]=useState('');
 const link=lobby?`${location.origin}${location.pathname}?join=${lobby.code}`:'';
 async function copy(text:string){try{await navigator.clipboard.writeText(text);setCopied('Copiado!');}catch{setCopied('Selecione e copie o texto do campo abaixo.');}}
 return <main className="home-shell"><header className="home-header"><HomeBrand/><button className="text-button" disabled={busy} onClick={onHome}>Home</button></header><section className="lobby-panel"><p className="eyebrow">SALA MULTIPLAYER / FLASHCART</p><h1>{!lobby?'Conectando à sala…':lobby.status==='closed'?'Sala encerrada':'Preparem suas mesas'}</h1>{error&&<p className="home-error" role="alert">{error}</p>}
 {lobby&&lobby.status!=='closed'&&<><p>Compartilhe o código com uma pessoa. A partida começa quando ambos estiverem prontos e o anfitrião iniciar.</p><div className="lobby-code"><label>Código de acesso<input readOnly value={lobby.code} onFocus={e=>e.target.select()}/></label><button className="secondary" onClick={()=>copy(lobby.code)}><Copy size={16}/> Copiar código</button></div><label>Link de convite<input readOnly value={link} onFocus={e=>e.target.select()}/></label><button className="text-button" onClick={()=>copy(link)}><Copy size={14}/> Copiar link</button><span className="copy-status" role="status">{copied}</span><div className="lobby-seats">{lobby.seats.map((seat,i)=><div key={i}><span className={`avatar avatar-${i}`}>{seat?.name[0]??'?'}</span><div><strong>{seat?.name??'Aguardando jogador'}</strong><small>{i===0?'Anfitrião':'Convidado'}{i===lobby.player?' · você':''}</small>{seat&&<small>{SPECIALTIES[seat.specialty]?.name}</small>}</div><span className="seat-status">{!seat?'Vaga livre':!lobby.online[i]?'Reconectando…':seat.ready?'Pronto ✓':'Conectado'}</span></div>)}</div><div className="lobby-actions"><button className="secondary" disabled={busy} onClick={()=>onAction('ready',!lobby.seats[lobby.player]?.ready)}>{lobby.seats[lobby.player]?.ready?'Cancelar prontidão':'Confirmar prontidão'}</button>{lobby.player===0?<button className="primary" disabled={busy||!lobby.seats.every(s=>s?.ready)||!lobby.online.every(Boolean)} onClick={()=>onAction('start')}><Play size={16}/> Iniciar partida</button>:<p>Aguardando o anfitrião iniciar.</p>}</div><p className="home-hint">A sala expira após 24 horas de espera. Na partida, quedas de conexão não pausam o relógio. Recarregar esta aba recupera sua sessão.</p><button className="text-button" disabled={busy} onClick={()=>onAction('leave')}>{lobby.player===0?'Encerrar sala':'Sair da sala'}</button></>}
 {lobby?.status==='closed'&&<><p>O anfitrião encerrou a sala ou o prazo de entrada expirou.</p><button className="primary" onClick={()=>onAction('dismiss')}>Voltar à home</button></>}
 </section></main>;
}
