import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,Check,X} from 'lucide-react';
import {EconomyExample,BuildExample,MarketExample,BudgetExample} from './TutorialExamples';
const lessons=[
 {title:'Uma loja. Duas arquiteturas.',text:'Você constrói o sistema da FlashCart, uma loja virtual que cresce e muda a cada rodada. O cenário é o mesmo para os dois jogadores; mão, backlog, decisões e arquitetura adversária ficam ocultos até o Showdown.',detail:'São cinco rodadas e seis testes finais. Uma tecnologia não é uma resposta certa: conexões, configuração e combinações determinam o comportamento.',visual:['Client','API','Banco / Pagamento']},
 {title:'Conheça suas cartas',text:'Seu baralho (deck) tem 24 cartas: 16 de base e 8 da especialização. Você recebe 5 cartas e pode trocar até 2, uma única vez e sem custo no setup. Depois, confirme “Estou pronto”.',detail:'A cada rodada você compra 1 carta. A mão comporta 7; a compra automática excedente vai ao descarte. O backlog guarda até 3 cartas. Não há reembaralhamento.',visual:['5 na mão','Troque até 2','Confirme o setup']},
 {title:'EC é esforço. Ação é uma jogada.',text:'EC são pontos de esforço da sua equipe. Ações são quantas jogadas você pode fazer na rodada. A sigla EC vem de Engineering Capacity, ou capacidade de engenharia.',detail:'Para implantar uma carta, você precisa de esforço suficiente e de uma jogada disponível. Veja a diferença abaixo.',visual:[],example:'economy'},
 {title:'O dinheiro mede outro custo',text:'O valor em $/mês mostra quanto custa manter o sistema funcionando depois de construído. O orçamento, também chamado de budget, é o limite mensal disponível.',detail:'Observe os três números separados na mesma carta.',visual:[],example:'budget'},
 {title:'Construa relações na mesa',text:'Selecione uma carta ou arraste para um encaixe destacado. Ajuste os parâmetros e prepare a implantação. Os destaques mostram compatibilidade estrutural, sem avaliar sua estratégia.',detail:'Uma réplica sem leituras direcionadas a ela pode só aumentar custo. Conectar, distribuir tráfego e configurar importa tanto quanto implantar. “Desfazer última” reverte decisões ainda não travadas.',visual:[],example:'build'},
 {title:'Dispute o mercado. Planeje a reserva.',text:'O mercado é compartilhado. Comprar custa 1 EC e 1 ação. Reservar uma carta da mão no backlog custa 1 EC e 1 ação; recuperar custa 1 ação e exige espaço na mão.',detail:'Tech Research consome 1 EC e 1 ação: revela até 3 cartas disponíveis, você escolhe 1 e descarta as outras. Essa informação não pode ser desfeita. Finalize a pesquisa antes de outra ação.',visual:[],example:'market'},
 {title:'45 segundos. Decisões simultâneas.',text:'Cada contexto abre 45 segundos de planejamento. Confirmar trava suas decisões; você aguarda na própria mesa. Quando ambos confirmam ou o prazo termina, o servidor resolve as ações.',detail:'No fim do prazo, jogadas preparadas são confirmadas e EC restante é preservado. Pesquisa pendente escolhe a primeira opção. Compra disputada usa prioridade determinística: quem perde mantém EC e ação e ganha 45 segundos para ajustar.',visual:['Cenário','Planejamento · 45 s','Telemetria · 8 s']},
 {title:'Leia sinais. Compare no Showdown.',text:'A telemetria mostra latência P95, erros, vazão e custo durante 8 segundos. Ambos podem avançar antes. Instrumentação revela mais detalhes; tracing ajuda a entender causas. Não há nota de jogada por rodada.',detail:'Após a quinta rodada, os grafos são revelados e congelados. Performance, disponibilidade, segurança, consistência, custo e resiliência têm o mesmo peso. Vence quem ganha mais categorias; empate usa desempenho normalizado, podendo terminar empatado.',visual:['5 rodadas','6 categorias','Mesmas condições']},
 {title:'Convide alguém para a mesa',text:'Crie uma sala e compartilhe o código ou o link. A outra pessoa escolhe nome e especialização e ocupa a segunda vaga. Ambos confirmam prontidão; o anfitrião inicia. Na mesa, cada um prepara sua mão antes da primeira rodada.',detail:'Use o mesmo endereço de servidor. Recarregar a aba recupera sua sessão. Se a conexão cair, os prazos continuam; reconectar recupera o estado oficial. O código serve para entrar, não para recuperar uma vaga já ocupada. Mantenha a aba para conservar sua credencial.',visual:['Criar / entrar','Ambos prontos','Anfitrião inicia']}
];
export default function Tutorial({onClose,initialStep=0}:{onClose:()=>void;initialStep?:number}){
 const [step,setStep]=useState(initialStep),heading=useRef<HTMLHeadingElement>(null),panel=useRef<HTMLElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement,overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=overflow;previous?.focus();};},[]);
 useEffect(()=>{heading.current?.focus();},[step]);
 const lesson=lessons[step];
 return <div className="tutorial-scrim" onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();onClose();}if(e.key==='Tab'){const items=panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),[tabindex="0"]');if(!items?.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===heading.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}><section ref={panel} className="tutorial-panel" role="dialog" aria-modal="true" aria-labelledby="tutorial-title">
 <header><span className="eyebrow"><BookOpen size={16}/> TUTORIAL · {step+1} / {lessons.length}</span><button className="icon-button" aria-label="Fechar tutorial" onClick={onClose}><X/></button></header>
 <div className="lesson-progress" aria-label={`Etapa ${step+1} de ${lessons.length}`}>{lessons.map((l,i)=><button key={l.title} className={i===step?'active':''} aria-label={`Etapa ${i+1}: ${l.title}`} aria-current={i===step?'step':undefined} onClick={()=>setStep(i)}/>)}</div>
 <h2 id="tutorial-title" tabIndex={-1} ref={heading}>{lesson.title}</h2><p>{lesson.text}</p><div className="lesson-visual" hidden={!lesson.visual.length}>{lesson.visual.map((v,i)=><span key={v}><b>0{i+1}</b>{v}</span>)}</div><p className="lesson-detail">{lesson.detail}</p>
 {lesson.example==='economy'&&<EconomyExample/>}
 {lesson.example==='budget'&&<BudgetExample/>}
 {lesson.example==='build'&&<BuildExample/>}
 {lesson.example==='market'&&<MarketExample/>}

 <footer><button className="secondary" disabled={step===0} onClick={()=>setStep(s=>s-1)}><ArrowLeft size={16}/> Anterior</button><button className="primary" onClick={()=>step===lessons.length-1?onClose():setStep(s=>s+1)}>{step===lessons.length-1?'Concluir tutorial':'Próxima etapa'}{step===lessons.length-1?<Check size={16}/>:<ArrowRight size={16}/>}</button></footer>
 </section></div>;
}
